version: '3.8'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./show_cook/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn show_cook.wsgi:application --bind 0.0.0.0:8000
      "

  frontend:
    build: ./frontend_react/
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/frontend_static
    command: >
      sh -c "
        npm install &&
        npm run build &&
        cp -r /app/build/. /frontend_static &&
        tail -f /dev/null
      "

  gateway:
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles:ro
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    entrypoint: ["nginx","-g","daemon off;"]
