# Generated by Django 5.1.7 on 2025-05-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_of_birth_user_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Date_of_birth",
            new_name="date_of_birth",
        ),
    ]
