openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/recipes/:
    get:
      operationId: listRecipes
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0441\u043E\
        \u0437\u0434\u0430\u043D\u0438\u044F \u0438 \u043F\u0440\u043E\u0441\u043C\
        \u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u0440\u0435\
        \u0446\u0435\u043F\u0442\u043E\u0432."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
    post:
      operationId: createRecipe
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0441\u043E\
        \u0437\u0434\u0430\u043D\u0438\u044F \u0438 \u043F\u0440\u043E\u0441\u043C\
        \u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u0440\u0435\
        \u0446\u0435\u043F\u0442\u043E\u0432."
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recipe'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
  /api/recipes/{id}/:
    get:
      operationId: retrieveRecipe
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F, \u043E\u0431\u043D\u043E\u0432\
        \u043B\u0435\u043D\u0438\u044F \u0438 \u0443\u0434\u0430\u043B\u0435\u043D\
        \u0438\u044F \u043E\u0434\u043D\u043E\u0433\u043E \u0440\u0435\u0446\u0435\
        \u043F\u0442\u0430 \u043F\u043E ID."
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this recipe.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
    put:
      operationId: updateRecipe
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F, \u043E\u0431\u043D\u043E\u0432\
        \u043B\u0435\u043D\u0438\u044F \u0438 \u0443\u0434\u0430\u043B\u0435\u043D\
        \u0438\u044F \u043E\u0434\u043D\u043E\u0433\u043E \u0440\u0435\u0446\u0435\
        \u043F\u0442\u0430 \u043F\u043E ID."
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this recipe.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recipe'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateRecipe
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F, \u043E\u0431\u043D\u043E\u0432\
        \u043B\u0435\u043D\u0438\u044F \u0438 \u0443\u0434\u0430\u043B\u0435\u043D\
        \u0438\u044F \u043E\u0434\u043D\u043E\u0433\u043E \u0440\u0435\u0446\u0435\
        \u043F\u0442\u0430 \u043F\u043E ID."
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this recipe.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recipe'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyRecipe
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F, \u043E\u0431\u043D\u043E\u0432\
        \u043B\u0435\u043D\u0438\u044F \u0438 \u0443\u0434\u0430\u043B\u0435\u043D\
        \u0438\u044F \u043E\u0434\u043D\u043E\u0433\u043E \u0440\u0435\u0446\u0435\
        \u043F\u0442\u0430 \u043F\u043E ID."
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this recipe.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/recipes/by-ingredients/:
    get:
      operationId: listRecipesByIngredients
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F \u0440\u0435\u0446\u0435\u043F\u0442\
        \u043E\u0432, \u0441\u043E\u0434\u0435\u0440\u0436\u0430\u0449\u0438\u0445\
        \ \u0443\u043A\u0430\u0437\u0430\u043D\u043D\u044B\u0435 \u0438\u043D\u0433\
        \u0440\u0435\u0434\u0438\u0435\u043D\u0442\u044B.\n\u041F\u0440\u0438\u043C\
        \u0435\u0440 \u0437\u0430\u043F\u0440\u043E\u0441\u0430: GET /api/recipes/by-ingredients/?ingredients=\u044F\
        \u0431\u043B\u043E\u043A\u043E,\u043C\u043E\u043B\u043E\u043A\u043E"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
          description: ''
      tags:
      - api
  /users/profile/:
    get:
      operationId: retrieveUser
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - users
    put:
      operationId: updateUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - users
    patch:
      operationId: partialUpdateUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - users
  /users/register/:
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
      tags:
      - users
  /users/login/:
    post:
      operationId: createAuthToken
      description: ''
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
      tags:
      - users
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        ingredients:
          type: array
          items:
            type: object
            properties:
              ingredient:
                type: string
              amount:
                type: string
                maxLength: 50
            required:
            - ingredient
            - amount
        link:
          type: string
          format: uri
          nullable: true
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
            .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
            ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\\
            .(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
            .?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
      required:
      - title
      - description
      - ingredients
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: "\u041E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\
            \u043E\u0435 \u043F\u043E\u043B\u0435. \u041D\u0435 \u0431\u043E\u043B\
            \u0435\u0435 150 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432. \u0422\
            \u043E\u043B\u044C\u043A\u043E \u0431\u0443\u043A\u0432\u044B, \u0446\u0438\
            \u0444\u0440\u044B \u0438 \u0441\u0438\u043C\u0432\u043E\u043B\u044B @/./+/-/_."
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        photo:
          type: string
          format: binary
          nullable: true
      required:
      - username
    Register:
      type: object
      properties:
        username:
          type: string
          description: "\u041E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\
            \u043E\u0435 \u043F\u043E\u043B\u0435. \u041D\u0435 \u0431\u043E\u043B\
            \u0435\u0435 150 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432. \u0422\
            \u043E\u043B\u044C\u043A\u043E \u0431\u0443\u043A\u0432\u044B, \u0446\u0438\
            \u0444\u0440\u044B \u0438 \u0441\u0438\u043C\u0432\u043E\u043B\u044B @/./+/-/_."
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
      required:
      - username
      - password
      - password2
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - username
      - password
